
import type { ProjectType, PriorityType } from '@/types';

export const PROJECT_TYPES: ProjectType[] = ["Produção de Vídeo", "Sites", "Software", "Contrato Mensal", "Drone", "Animação de Logomarca", "Gravação", "Edição", "Instagram", "Fotos Profissionais"];

export const PRIORITIES: PriorityType[] = ["Baixa", "Média", "Alta"];

export const PROJECT_STATUS_OPTIONS: Record<ProjectType, string[]> = {
  "Produção de Vídeo": [
    "Aguardando Início",
    "Gravação Agendada",
    "Gravação Concluída",
    "Edição em Andamento",
    "Edição Finalizada",
    "Revisão do Cliente",
    "Em Pausa",
    "Bloqueado",
    "Projeto Concluído",
  ],
  "Sites": [
    "Briefing e Planejamento",
    "Design (UI/UX)",
    "Desenvolvimento Frontend",
    "Desenvolvimento Backend",
    "Revisão e Testes",
    "Lançamento",
    "Manutenção e Suporte",
    "Projeto Concluído",
  ],
  "Software": [
    "Levantamento de Requisitos",
    "Design de Arquitetura",
    "Desenvolvimento",
    "Testes (QA)",
    "Implantação (Deploy)",
    "Operação e Manutenção",
    "Descontinuado",
    "Projeto Concluído",
  ],
  "Contrato Mensal": [
    "Ativo",
    "Em Pausa",
    "Aguardando Pagamento",
    "Finalizado",
  ],
  "Drone": [
    "Planejamento de Voo",
    "Voo Agendado",
    "Voo Realizado",
    "Processamento de Imagens",
    "Material Entregue",
    "Projeto Concluído",
  ],
  "Animação de Logomarca": [
    "Animação em Produção",
    "Edição e Finalização",
    "Revisão do Cliente",
    "Entrega do Arquivo Final",
    "Projeto Concluído",
  ],
  "Gravação": [
    "Aguardando Agendamento",
    "Pré-produção e Planejamento",
    "Gravação Agendada",
    "Em Gravação",
    "Gravação Concluída",
    "Material Bruto Entregue",
    "Revisão de Material",
    "Refação Agendada",
    "Projeto Concluído",
  ],
  "Edição": [
    "Aguardando Material Bruto",
    "Material Recebido e Organizado",
    "Decupagem e Seleção de Takes",
    "Primeira Montagem (Rough Cut)",
    "Edição Detalhada (Fine Cut)",
    "Aplicação de Efeitos Visuais e Transições",
    "Tratamento de Cor (Color Grading/Correction)",
    "Mixagem de Áudio e Sound Design",
    "Adição de Trilha Sonora e Efeitos Sonoros (SFX)",
    "Criação e Inserção de Legendas/Gráficos",
    "Versão para Revisão Interna",
    "Versão para Revisão do Cliente",
    "Ajustes Finais Pós-Revisão",
    "Exportação Final (Masterização)",
    "Projeto Concluído",
  ],
  "Instagram": [
    "Planejamento Estratégico Mensal/Semanal",
    "Criação de Pauta de Conteúdo",
    "Design de Criativos Estáticos (Posts, Stories)",
    "Roteirização de Vídeos (Reels, Stories)",
    "Captação/Produção de Vídeos",
    "Edição de Vídeos para Instagram",
    "Redação de Legendas (Copywriting) e Pesquisa de Hashtags",
    "Agendamento de Publicações",
    "Publicação Realizada",
    "Monitoramento de Engajamento e Interação",
    "Análise de Métricas e Relatório de Performance",
    "Ciclo de Conteúdo Concluído",
  ],
  "Fotos Profissionais": [
    "Aguardando Agendamento",
    "Sessão Agendada",
    "Sessão Realizada",
    "Fotos em Tratamento",
    "Fotos Entregues",
    "Projeto Concluído",
  ],
  // Programação foi removido
  "Programação": [],
};

export const INITIAL_PROJECT_STATUS = (type: ProjectType): string => {
    const statuses = PROJECT_STATUS_OPTIONS[type];
    if (statuses.includes("Aguardando Início")) {
      return "Aguardando Início";
    }
    if (type === "Gravação" && statuses.includes("Aguardando Agendamento")) {
      return "Aguardando Agendamento";
    }
    if (type === "Edição" && statuses.includes("Aguardando Material Bruto")) {
      return "Aguardando Material Bruto";
    }
     if (type === "Instagram" && statuses.includes("Planejamento Estratégico Mensal/Semanal")) {
      return "Planejamento Estratégico Mensal/Semanal";
    }
    if (type === "Fotos Profissionais" && statuses.includes("Aguardando Agendamento")) {
      return "Aguardando Agendamento";
    }
    return statuses.length > 0 ? statuses[0] : "";
}

export const PREDEFINED_CHECKLISTS: Record<ProjectType, string[]> = {
  "Produção de Vídeo": [
    "Briefing e Roteiro definidos",
    "Equipamentos reservados/preparados",
    "Locações definidas e liberadas",
    "Agendamento de equipe e talentos",
    "Captação de imagens e áudio",
    "Backup de material bruto",
    "Decupagem do material",
    "Primeira montagem (offline)",
    "Trilha sonora e efeitos sonoros",
    "Colorização e tratamento de imagem",
    "Motion graphics e legendas (se houver)",
    "Exportação para revisão interna",
    "Ajustes pós-revisão interna",
    "Exportação para revisão do cliente",
    "Ajustes pós-revisão do cliente",
    "Exportação final e entrega",
  ],
  "Sites": [
    "Levantamento de requisitos e briefing",
    "Definição da arquitetura e mapa do site",
    "Criação de Wireframes e protótipos",
    "Design de UI/UX aprovado",
    "Configuração do ambiente de desenvolvimento (local e staging)",
    "Desenvolvimento do frontend",
    "Desenvolvimento do backend e integrações (CMS, APIs)",
    "Testes de responsividade em múltiplos dispositivos",
    "Testes de funcionalidade e QA (Quality Assurance)",
    "Otimização de performance (velocidade de carregamento, SEO básico)",
    "Revisão e aprovação pelo cliente",
    "Configuração do ambiente de produção (hospedagem, domínio, SSL)",
    "Migração de conteúdo (se aplicável)",
    "Lançamento do site (deploy)",
    "Monitoramento pós-lançamento",
  ],
  "Software": [
    "Análise de Requisitos e Escopo do Projeto",
    "Elaboração da Especificação Funcional e Técnica",
    "Design da Arquitetura do Software",
    "Prototipagem e Design de Interface (UI/UX)",
    "Configuração dos Ambientes (Desenvolvimento, Testes, Produção)",
    "Desenvolvimento de Módulos/Features (Sprints)",
    "Testes Unitários e de Integração contínuos",
    "Ciclos de Testes de Qualidade (QA)",
    "Processo de Build e Deploy Automatizado (CI/CD)",
    "Testes de Aceitação do Usuário (UAT)",
    "Documentação Técnica e de Usuário",
    "Treinamento de Usuários",
    "Lançamento (Go-live)",
    "Plano de Suporte e Manutenção",
  ],
  "Contrato Mensal": [
    "Reunião de alinhamento inicial (Kick-off)",
    "Definição de escopo e entregáveis mensais",
    "Estabelecimento de canais de comunicação e pontos de contato",
    "Primeira entrega de atividades",
    "Reunião de acompanhamento semanal/quinzenal",
    "Relatório de performance mensal",
    "Faturamento e pagamento",
    "Planejamento do próximo ciclo/mês",
    "Renovação ou encerramento do ciclo de contrato",
  ],
  "Drone": [
    "Briefing e definição dos objetivos da captura",
    "Análise de viabilidade e riscos do local",
    "Obtenção de autorizações de voo (se necessário)",
    "Planejamento da missão de voo (rotas, altitudes, parâmetros da câmera)",
    "Checklist de segurança e preparação dos equipamentos (drone, baterias, câmera)",
    "Execução do voo e captura de imagens/vídeos",
    "Backup seguro do material capturado",
    "Processamento das imagens (fotogrametria, se aplicável)",
    "Edição e tratamento do vídeo ou fotos",
    "Geração dos entregáveis (mapas, modelos 3D, vídeo final)",
    "Entrega e apresentação dos resultados ao cliente",
  ],
  "Animação de Logomarca": [
    "Recebimento e análise do briefing",
    "Pesquisa de referências e estilos",
    "Criação de storyboard/animatic",
    "Aprovação do storyboard pelo cliente",
    "Design dos elementos gráficos (se necessário)",
    "Animação dos elementos",
    "Sincronização com áudio (trilha/efeitos)",
    "Renderização prévia para revisão",
    "Ajustes pós-revisão interna/cliente",
    "Renderização final em alta qualidade",
    "Entrega dos arquivos nos formatos solicitados",
  ],
  "Gravação": [
    "Briefing e roteiro/shotlist recebidos e analisados",
    "Locações definidas, vistoriadas e liberadas",
    "Equipamentos de gravação (câmeras, lentes, áudio, iluminação) checados e preparados",
    "Equipe técnica (cinegrafista, assistente, técnico de som) confirmada",
    "Talentos, atores ou apresentadores confirmados e alinhados",
    "Agendamento de diárias de gravação e cronograma detalhado",
    "Transporte e logística de equipamentos e equipe organizados",
    "Permissões de gravação e autorizações de imagem obtidas (se necessário)",
    "Captação de todas as cenas, takes e ângulos planejados",
    "Captação de áudio de alta qualidade (ambiente, entrevistas, etc.)",
    "Realização de backups do material bruto em diferentes mídias",
    "Organização inicial e nomeação dos arquivos de mídia",
    "Envio ou entrega física do material bruto para a equipe de edição ou cliente",
  ],
  "Edição": [
    "Recebimento completo do material bruto (vídeo, áudio, fotos) e assets (logos, fontes)",
    "Briefing de edição compreendido (referências, estilo, objetivos)",
    "Organização do projeto de edição (pastas, sequências, proxies se necessário)",
    "Sincronização de áudio e vídeo (se gravados separadamente)",
    "Decupagem e seleção dos melhores takes e momentos",
    "Montagem da estrutura principal da narrativa (rough cut)",
    "Refinamento de cortes, ritmo, timing e continuidade (fine cut)",
    "Aplicação de correções de cor primárias e secundárias (color grading)",
    "Tratamento de áudio (limpeza, equalização, normalização de níveis)",
    "Design de som (adição de efeitos sonoros, ambientação)",
    "Inclusão e sincronização de trilha sonora licenciada/aprovada",
    "Criação e inserção de letterings, legendas, lower thirds e outros gráficos",
    "Renderização da primeira versão para revisão (baixa resolução, se necessário)",
    "Coleta e organização do feedback do cliente/diretor",
    "Implementação precisa das revisões solicitadas",
    "Checagem final de qualidade (áudio, vídeo, sincronia, legendas)",
    "Exportação nos formatos e especificações finais solicitados",
    "Entrega dos arquivos finalizados e do projeto de edição (se acordado)",
  ],
  "Instagram": [
    "Definição de objetivos para o período (ex: aumento de seguidores, engajamento, vendas)",
    "Análise do público-alvo e persona",
    "Pesquisa de temas, tendências e concorrentes",
    "Criação do calendário editorial (datas, horários, formatos, temas, pilares de conteúdo)",
    "Aprovação do calendário editorial pelo cliente",
    "Brainstorm de ideias para posts estáticos (imagens únicas, carrosséis, quotes)",
    "Criação ou seleção de imagens/vídeos de banco (se aplicável)",
    "Design dos criativos utilizando identidade visual do cliente",
    "Redação das legendas para posts estáticos, CTAs (Call to Action) e hashtags relevantes",
    "Revisão interna de design e texto (estático)",
    "Aprovação dos posts estáticos pelo cliente",
    "Brainstorm e roteirização dos vídeos (Reels/Stories)",
    "Planejamento de cenas para vídeos, áudios em alta e efeitos",
    "Captação/Gravação do material bruto para vídeos",
    "Edição dos vídeos (cortes, transições, música, texto sobreposto, legendas)",
    "Redação das legendas para vídeos, CTAs e hashtags",
    "Revisão interna do vídeo",
    "Aprovação dos vídeos pelo cliente",
    "Agendamento dos posts em ferramenta de gerenciamento ou manualmente",
    "Verificação final de links, tags e detalhes antes da publicação",
    "Confirmação da publicação no horário agendado",
    "Monitorar comentários e mensagens diretas (DMs)",
    "Responder dúvidas e interagir com a audiência de forma ágil e adequada",
    "Fomentar a participação em enquetes, caixas de perguntas, etc.",
    "Coleta de dados de performance (alcance, impressões, engajamento, cliques, etc.)",
    "Análise dos resultados em relação aos objetivos definidos",
    "Elaboração do relatório de performance com insights e recomendações",
    "Apresentação ou envio do relatório ao cliente",
  ],
  "Fotos Profissionais": [
    "Alinhamento de expectativas e briefing com o cliente.",
    "Definição e agendamento da data, horário e local da sessão.",
    "Confirmação da sessão com o cliente.",
    "Realização da sessão fotográfica.",
    "Backup das fotos e seleção das melhores imagens.",
    "Tratamento básico das fotos selecionadas (ajustes de cor, luz, contraste, enquadramento).",
    "Envio do link ou galeria com as fotos tratadas para o cliente.",
    "Confirmação de recebimento e aprovação pelo cliente.",
  ],
  // Programação foi removido
  "Programação": [],
};
